In [1]:
import numpy as np

## Statistical oriented- mean, median, mode, std

- mean ->Average
- mode->The most repeated number 
- median -> the middle num, values should be in ascending order 
- std


In [2]:
marks=np.random.randint(40,100,10)
print(marks)

[46 62 52 46 43 99 81 53 94 85]


In [4]:
print(marks.mean())

66.1


In [5]:
print(np.median(marks))

57.5


In [6]:
print(marks.std())

20.417884317431128


In [7]:
print(np.std(marks))

20.417884317431128


In [ ]:
P = 1000
i = 1
while i < 11:
    P = P * 1.05
    print(f"year{i} = R{P}")
    i += 1


year1 = R1050.0
year2 = R1102.5
year3 = R1157.625
year4 = R1215.5062500000001
year5 = R1276.2815625000003
year6 = R1340.0956406250004
year7 = R1407.1004226562504
year8 = R1477.455443789063
year9 = R1551.3282159785163
year10 = R1628.8946267774422


In [15]:
investment_amount = 1_000
interest_rate = 1.05
num_years = np.arange(1, 11)


amount = investment_amount * interest_rate** num_years

print(amount)


[1050.         1102.5        1157.625      1215.50625    1276.2815625
 1340.09564063 1407.10042266 1477.45544379 1551.32821598 1628.89462678]


In [19]:
print(f"At the end of the 10th year the balance will be: R{round(amount[-1],2)}")

At the end of the 10th year the balance will be: R1628.89


In [26]:
a=((amount[-1])/(investment_amount)-1)*100
print(a)

62.8894626777442


In [ ]:
### Task 2



P = 1000
i = 1
while i < 11:
    P = P * 1.05
    #print(f"year{i} = R{P}")
    i += 1
print(f"At the end of the 10th year the balance will be: {P}")

At the end of the 10th year the balance will be: 1628.8946267774422


In [14]:
print((P/1000))

1.6288946267774422


In [27]:
num=np.random.randint(1,4,10)
num

array([1, 3, 3, 3, 1, 2, 3, 3, 2, 3], dtype=int32)

In [32]:
np.flip(num)

array([3, 2, 3, 3, 2, 1, 3, 3, 3, 1], dtype=int32)

## Task 1
 
hourly_visitors = [468, 279,  73, 272 ,406 ,128 ,302 ,216, 140, 82]
 
- 1.1 Total visitors in the day?
- 1.2 Which is the peak hour?
- 1.3 On average how many people visit per hour
 
### Output
```
Total visitors in the day: 2366
Peak hour: 1
Average people visit: 237
```

In [33]:
hourly_visitors = [468, 279, 73, 272, 406, 128, 302, 216, 140, 82]


In [ ]:
a=sum(hourly_visitors)
print(f"Total visitors in a day: {a}")

b=np.argmax(hourly_visitors)+1
print(f"Peak hour: {b}")

c=round(np.mean(hourly_visitors))
print(f"Average people visit: {c}")


Total visitors in a day: 2366
Peak hour: 1
Average people visit: 237


## Task 2
Normalize the Array:
 
- 2.1 Trim leading and trailing spaces.
- 2.2 Convert all items to lowercase.
- 2.3 Ensure there are no duplicate items in the array.

In [42]:
items = np.array(
    [
        " Apple",
        "banana ",
        "GRAPE",
        "cucumber",
        "Pineapple",
        " tomato ",
        "Orange",
        " lemon",
        "Kiwi ",
        "mango",
        "blueberry ",
        " raspberry",
    ]
)


In [51]:
items1=np.char.strip(items)
items1

array(['Apple', 'banana', 'GRAPE', 'cucumber', 'Pineapple', 'tomato',
       'Orange', 'lemon', 'Kiwi', 'mango', 'blueberry', 'raspberry'],
      dtype='<U10')

In [52]:
items1=np.char.lower(items)
items1

array([' apple', 'banana ', 'grape', 'cucumber', 'pineapple', ' tomato ',
       'orange', ' lemon', 'kiwi ', 'mango', 'blueberry ', ' raspberry'],
      dtype='<U10')

In [47]:
np.unique(items1)

array([' apple', ' lemon', ' raspberry', ' tomato ', 'banana ',
       'blueberry ', 'cucumber', 'grape', 'kiwi ', 'mango', 'orange',
       'pineapple'], dtype='<U10')

## Task 3 (Challenging)
Filtering Operations:
- 3.1 Find and display all items that start with the letter 'b'.
- 3.2 Find and display all items that contain the letter 'e' exactly once.

In [56]:
new=np.char.strip(items1)
new

array(['apple', 'banana', 'grape', 'cucumber', 'pineapple', 'tomato',
       'orange', 'lemon', 'kiwi', 'mango', 'blueberry', 'raspberry'],
      dtype='<U10')

In [57]:
new

array(['apple', 'banana', 'grape', 'cucumber', 'pineapple', 'tomato',
       'orange', 'lemon', 'kiwi', 'mango', 'blueberry', 'raspberry'],
      dtype='<U10')

In [62]:
print(new[np.char.startswith(new, "b")])

['banana' 'blueberry']


In [67]:
mask = np.char.count(new, "e") > 0
print(new[mask])

['apple' 'grape' 'cucumber' 'pineapple' 'orange' 'lemon' 'blueberry'
 'raspberry']


In [68]:
b = np.strings.count(new, "e")

print(new[b == 1])


['apple' 'grape' 'cucumber' 'orange' 'lemon' 'raspberry']


## 2D Matrix/Array



In [69]:
num3x3 = np.array([[1,3,4],
                   [6,10,77],
                   [9,20,24]


])

In [70]:
np.shape(num3x3)

(3, 3)

In [72]:
num3x3 * 2

array([[  2,   6,   8],
       [ 12,  20, 154],
       [ 18,  40,  48]])