In [2]:
import numpy as np

In [3]:
marks1=[90,80,20,40]
print(marks1*2)

[90, 80, 20, 40, 90, 80, 20, 40]


In [4]:
marks2 = np.array([90, 80, 20, 40])
print(marks2*2)

[180 160  40  80]


In [8]:
a=[x*2 for x in marks2]
print(a)

[np.int64(180), np.int64(160), np.int64(40), np.int64(80)]


In [9]:
marks1 =  [90, 80, 20, 40]
print([x*2 for x in marks1])

[180, 160, 40, 80]


In [10]:
5*np.ones(20)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

In [11]:
print(np.zeros(20) +5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
np.arange(1,11)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

## Operations
- Multiply, Division, Addition, Subtraction
- Boolean matrix Filter

In [17]:
np.arange(1,11)*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [19]:
np.arange(1,11)+np.arange(1,11)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
np.arange(1,11)>5 ##boolean matrix

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [23]:
first_tens=np.arange(1,11)
only_five_bm = first_tens>5
first_tens[only_five_bm]

array([ 6,  7,  8,  9, 10])

In [ ]:
np.arange(1,201,2)

In [ ]:
num = np.arange(1, 201)
even_numbers = num[num % 2 == 0]  ## important !!!
even_numbers

In [31]:
np.random.randint(16,80,5)

array([63, 47, 54, 43, 28], dtype=int32)